//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomKarakuyumjyan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ДипломEntities : DbContext
    {
        public ДипломEntities()
            : base("name=ДипломEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Адреса> Адреса { get; set; }
        public virtual DbSet<ВидыРабот> ВидыРабот { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Отчеты> Отчеты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Работники> Работники { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<СтатусРаботы> СтатусРаботы { get; set; }
    }
}
