//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomKarakuyumjyan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.Отчеты = new HashSet<Отчеты>();
        }
    
        public int IDЗаявки { get; set; }
        public int IDКлиента { get; set; }
        public Nullable<System.DateTime> ПлановаяДатаНачалаРабот { get; set; }
        public Nullable<System.DateTime> ПлановаяДатаОкончанияРабот { get; set; }
        public int IDСтатуса { get; set; }
        public int IDВида { get; set; }
        public int IDРаботника { get; set; }
        public int IDАдреса { get; set; }
        public int IDПользователя { get; set; }
    
        public virtual Адреса Адреса { get; set; }
        public virtual ВидыРабот ВидыРабот { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Работники Работники { get; set; }
        public virtual СтатусРаботы СтатусРаботы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчеты> Отчеты { get; set; }
    }
}
